In [3]:
import plotly.express as px
import pandas as pd
import numpy as np

In [7]:
acculturation_2011_df = pd.read_csv('../data/raw/2011-2012_acculturation.csv')
alcohol_use_2011_df = pd.read_csv('../data/raw/2011-2012_alcohol_use.csv')
bp_cholesterol_2011_df = pd.read_csv('../data/raw/2011-2012_bp_cholesterol.csv')
#oops
cardiovascular_2011_df = pd.read_csv('../data/raw/2011-2012_cardiovascular.csv')
consumer_behavior_2011_df = pd.read_csv('../data/raw/2011-2012_consumer_behavior.csv')
demographic_2011_df = pd.read_csv('../data/raw/2011-2012_demographic.csv')
dermatology_2011_df = pd.read_csv('../data/raw/2011-2012_dermatology.csv')
diabetes_2011_df = pd.read_csv('../data/raw/2011-2012_diabetes.csv')
diet_nutrition_2011_df = pd.read_csv('../data/raw/2011-2012_diet_nutrition.csv')
#I'll just test it out first because I don't want this to be a pain later (in case it doesn't work)
#Yup, it doesn't work
# Ohhh, thank you! I do the same thing but for tabbing, I didn't know it would work for comments
drug_use_2011_df = pd.read_csv('../data/raw/2011-2012_drug_use.csv')
early_childhood_2011_df = pd.read_csv('../data/raw/2011-2012_early_childhood.csv')
food_security_2011_df = pd.read_csv('../data/raw/2011-2012_food_security.csv')
health_insurance_2011_df = pd.read_csv('../data/raw/2011-2012_health_insurance.csv')
health_status_2011_df = pd.read_csv('../data/raw/2011-2012_health_status.csv')
hospital_access_to_care_2011_df = pd.read_csv('../data/raw/2011-2012_hospital_access_to_care.csv')
housing_2011_df = pd.read_csv('../data/raw/2011-2012_housing.csv')
immunization_2011_df = pd.read_csv('../data/raw/2011-2012_immunization.csv')
income_2011_df = pd.read_csv('../data/raw/2011-2012_income.csv')
medical_conditions_2011_df = pd.read_csv('../data/raw/2011-2012_medical_conditions.csv')
mental_health_2011_df = pd.read_csv('../data/raw/2011-2012_mental_health.csv')
occupation_2011_df = pd.read_csv('../data/raw/2011-2012_occupation.csv')
oral_health_2011_df = pd.read_csv('../data/raw/2011-2012_oral_health.csv')
pesticide_use_2011_df = pd.read_csv('../data/raw/2011-2012_pesticide_use.csv')
# I can't believe I'm not done yet
physical_activity_2011_df = pd.read_csv('../data/raw/2011-2012_physical_activity.csv')
physical_functioning_2011_df = pd.read_csv('../data/raw/2011-2012_physical_functioning.csv')
preventative_aspirin_use_2011_df = pd.read_csv('../data/raw/2011-2012_preventative_aspirin_use.csv')
reproductive_2011_df = pd.read_csv('../data/raw/2011-2012_reproductive.csv')
sexual_behavior_2011_df = pd.read_csv('../data/raw/2011-2012_sexual_behavior.csv')
sleep_disorder_2011_df = pd.read_csv('../data/raw/2011-2012_sleep_disorder.csv')
smoking_cigarette_2011_df = pd.read_csv('../data/raw/2011-2012_smoking_cigarette.csv')
smoking_recent_tobacco_2011_df = pd.read_csv('../data/raw/2011-2012_smoking_recent_tobacco.csv')
urology_2011_df = pd.read_csv('../data/raw/2011-2012_urology.csv')
weight_history_2011_df = pd.read_csv('../data/raw/2011-2012_weight_history.csv')
#Done! Yay!!
#Actually, I think I had this issue before
#Yes

In [8]:
# clap clap clap
# Thank you, Michael
# Thanks, everyone!

In [14]:
#all_2011_df = acculturation_2011_df.merge(alcohol_use_2011_df, bp_cholesterol_2011_df, how='outer')
all_2011_df = acculturation_2011_df.merge(alcohol_use_2011_df, how='outer')
# okay, let's use a loop
df_list = [alcohol_use_2011_df,
            bp_cholesterol_2011_df, 
           cardiovascular_2011_df,
          consumer_behavior_2011_df, 
          demographic_2011_df,
           dermatology_2011_df,
           diabetes_2011_df,
           diet_nutrition_2011_df,
           drug_use_2011_df, 
           early_childhood_2011_df,
           food_security_2011_df,
           health_insurance_2011_df, 
           health_status_2011_df, 
           hospital_access_to_care_2011_df, 
           housing_2011_df,
           immunization_2011_df,
           income_2011_df,
           medical_conditions_2011_df,
           mental_health_2011_df,
           occupation_2011_df,
           oral_health_2011_df,
           pesticide_use_2011_df,
           physical_activity_2011_df,
           physical_functioning_2011_df,
           preventative_aspirin_use_2011_df,
           reproductive_2011_df,
           sexual_behavior_2011_df,
           sleep_disorder_2011_df,
           smoking_cigarette_2011_df,
           smoking_recent_tobacco_2011_df,
           urology_2011_df,
           weight_history_2011_df, 
          ]
for df in df_list:
    all_2011_df = all_2011_df.merge(df, how='outer')

all_2011_df

,SEQN,ACD011A,ACD011B,ACD011C,ACD040,ACD110,ALQ101,ALQ110,ALQ120Q,ALQ120U,...,WHD080Q,WHD080R,WHD080S,WHD080T,WHD080L,WHD110,WHD120,WHD130,WHD140,WHQ150
0,62161.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62163.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62164.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.0,NaN,NaN,NaN,NaN,145.0,118.0,NaN,172.0,38.0
3,62165.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62169.0,NaN,NaN,NaN,NaN,5.0,1.0,NaN,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9751,71903.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9752,71905.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9753,71906.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9754,71910.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9755,71914.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Yay!

In [15]:
all_2011_df.to_csv('all_2011_df.csv', index=False)
# what does it mean?
# yes
# yes
# it's done running